"use client";

import { useState } from "react";
import type { EscalationReport } from "@/lib/types";
import { CountdownTimer } from "./CountdownTimer";
import { SimpleMarkdown } from "./DecisionDetail";

interface EscalationPanelProps {
  report: EscalationReport;
}

export function EscalationPanel({ report }: EscalationPanelProps) {
  const [reviewState, setReviewState] = useState<
    "pending" | "approving" | "denying" | "approved" | "denied"
  >(report.status === "pending" ? "pending" : report.status);
  const [reviewError, setReviewError] = useState<string | null>(null);
  const [isExpired, setIsExpired] = useState(false);

  async function handleReview(action: "approve" | "deny") {
    setReviewState(action === "approve" ? "approving" : "denying");
    setReviewError(null);
    try {
      await fetch(`/api/escalations/${report.id}/review`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action }),
      });
      setReviewState(action === "approve" ? "approved" : "denied");
    } catch {
      setReviewState("pending");
      setReviewError(`Failed to ${action} — check connection and retry`);
    }
  }

  const isActioning = reviewState === "approving" || reviewState === "denying";
  const isDone = reviewState === "approved" || reviewState === "denied";

  return (
    <div className="flex flex-col gap-4 overflow-y-auto p-4">
      {/* Urgent decision callout with countdown */}
      <div className="rounded-lg border-l-4 border-verdict-escalate bg-verdict-escalate/10 px-4 py-3">
        <div className="flex items-center justify-between">
          <span className="text-sm font-bold text-verdict-escalate">Human Review Required</span>
          <CountdownTimer resetKey={report.id} onExpire={() => setIsExpired(true)} />
        </div>
        <p className="mt-1 text-[10px] text-verdict-escalate/70">
          {report.target}{report.version ? ` v${report.version}` : ""} — generated by {report.generated_by}
        </p>
      </div>

      {/* Signal summary */}
      <div className="rounded border border-surface-2 p-3">
        <h3 className="mb-2 text-xs font-semibold uppercase text-foreground/50">
          Signal Summary
        </h3>
        <div className="flex flex-col gap-2">
          {/* Reputation score bar */}
          <div>
            <div className="flex items-center justify-between text-[10px]">
              <span className="text-foreground/50">Reputation Score</span>
              <span className="text-foreground/70">
                {report.signals.reputation_score.toFixed(1)}
              </span>
            </div>
            <div className="mt-1 h-1.5 overflow-hidden rounded-full bg-surface-2">
              <div
                className={`h-full rounded-full ${
                  report.signals.reputation_score < 0.4
                    ? "bg-verdict-block"
                    : report.signals.reputation_score < 0.7
                      ? "bg-verdict-escalate"
                      : "bg-verdict-allow"
                }`}
                style={{
                  width: `${report.signals.reputation_score * 100}%`,
                }}
              />
            </div>
          </div>
          {/* Confidence vs threshold */}
          <div className="flex items-center justify-between text-[10px]">
            <span className="text-foreground/50">Confidence</span>
            <span
              className={
                report.signals.confidence < report.signals.threshold
                  ? "text-verdict-block"
                  : "text-verdict-allow"
              }
            >
              {(report.signals.confidence * 100).toFixed(0)}% (threshold:{" "}
              {(report.signals.threshold * 100).toFixed(0)}%)
            </span>
          </div>
        </div>
      </div>

      {/* Body markdown */}
      <div className="text-xs">
        <SimpleMarkdown content={report.body_markdown} />
      </div>

      {/* Review error */}
      {reviewError && (
        <p className="text-xs text-verdict-block">{reviewError}</p>
      )}

      {/* Action buttons */}
      <div className="flex gap-2 pt-2">
        {isDone ? (
          <div
            className={`w-full rounded-lg px-4 py-3 text-center text-sm font-bold ${
              reviewState === "approved"
                ? "bg-verdict-allow/20 text-verdict-allow"
                : "bg-verdict-block/20 text-verdict-block"
            }`}
          >
            {reviewState === "approved" ? "Approved" : "Denied"}
          </div>
        ) : (
          <>
            <button
              onClick={() => handleReview("approve")}
              disabled={isActioning || isExpired}
              className="flex-1 rounded-lg bg-verdict-allow px-4 py-3 text-sm font-bold text-white transition-opacity hover:opacity-90 disabled:opacity-40"
            >
              {reviewState === "approving" ? "Approving..." : "Approve"}
            </button>
            <button
              onClick={() => handleReview("deny")}
              disabled={isActioning || isExpired}
              className="flex-1 rounded-lg bg-verdict-block px-4 py-3 text-sm font-bold text-white transition-opacity hover:opacity-90 disabled:opacity-40"
            >
              {reviewState === "denying" ? "Denying..." : "Deny"}
            </button>
          </>
        )}
      </div>
    </div>
  );
}
