"use client";

import { useState } from "react";
import type { EscalationReport } from "@/lib/types";
import { CountdownTimer } from "./CountdownTimer";

interface EscalationPanelProps {
  report: EscalationReport;
}

export function EscalationPanel({ report }: EscalationPanelProps) {
  const [reviewState, setReviewState] = useState<
    "pending" | "approving" | "denying" | "approved" | "denied"
  >(report.status === "pending" ? "pending" : report.status);

  async function handleReview(action: "approve" | "deny") {
    setReviewState(action === "approve" ? "approving" : "denying");
    try {
      await fetch(`/api/escalations/${report.id}/review`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action }),
      });
      setReviewState(action === "approve" ? "approved" : "denied");
    } catch {
      setReviewState("pending");
    }
  }

  const isActioning = reviewState === "approving" || reviewState === "denying";
  const isDone = reviewState === "approved" || reviewState === "denied";

  return (
    <div className="flex flex-col gap-4 overflow-y-auto p-4">
      {/* Header */}
      <div>
        <h2 className="text-lg font-semibold text-verdict-escalate">
          Risk Assessment: {report.target}
        </h2>
        {report.version && (
          <span className="text-xs text-foreground/50">v{report.version}</span>
        )}
      </div>

      {/* Meta section */}
      <div className="flex items-center justify-between text-xs text-foreground/40">
        <span>Generated by: {report.generated_by}</span>
        <span>{new Date(report.timestamp).toLocaleString()}</span>
      </div>

      {/* Countdown timer */}
      <div className="flex items-center gap-2 rounded bg-surface-2 px-3 py-1.5">
        <span className="text-xs text-foreground/50">Expires in:</span>
        <CountdownTimer resetKey={report.id} />
      </div>

      {/* Signal summary */}
      <div className="rounded border border-surface-2 p-3">
        <h3 className="mb-2 text-xs font-semibold uppercase text-foreground/50">
          Signal Summary
        </h3>
        <div className="flex flex-col gap-2">
          {/* Reputation score bar */}
          <div>
            <div className="flex items-center justify-between text-[10px]">
              <span className="text-foreground/50">Reputation Score</span>
              <span className="text-foreground/70">
                {report.signals.reputation_score.toFixed(1)}
              </span>
            </div>
            <div className="mt-1 h-1.5 overflow-hidden rounded-full bg-surface-2">
              <div
                className={`h-full rounded-full ${
                  report.signals.reputation_score < 0.4
                    ? "bg-verdict-block"
                    : report.signals.reputation_score < 0.7
                      ? "bg-verdict-escalate"
                      : "bg-verdict-allow"
                }`}
                style={{
                  width: `${report.signals.reputation_score * 100}%`,
                }}
              />
            </div>
          </div>
          {/* Confidence vs threshold */}
          <div className="flex items-center justify-between text-[10px]">
            <span className="text-foreground/50">Confidence</span>
            <span
              className={
                report.signals.confidence < report.signals.threshold
                  ? "text-verdict-block"
                  : "text-verdict-allow"
              }
            >
              {(report.signals.confidence * 100).toFixed(0)}% (threshold:{" "}
              {(report.signals.threshold * 100).toFixed(0)}%)
            </span>
          </div>
        </div>
      </div>

      {/* Body markdown (simple rendering) */}
      <div className="flex flex-col gap-2 text-xs text-foreground/70">
        {report.body_markdown.split("\n\n").map((para, i) => (
          <p key={i}>{para}</p>
        ))}
      </div>

      {/* Action buttons */}
      <div className="flex gap-2 pt-2">
        {isDone ? (
          <div
            className={`w-full rounded px-3 py-2 text-center text-xs font-semibold ${
              reviewState === "approved"
                ? "bg-verdict-allow/15 text-verdict-allow"
                : "bg-verdict-block/15 text-verdict-block"
            }`}
          >
            {reviewState === "approved" ? "Approved" : "Denied"}
          </div>
        ) : (
          <>
            <button
              onClick={() => handleReview("approve")}
              disabled={isActioning}
              className="flex-1 rounded bg-verdict-allow/15 px-3 py-2 text-xs font-semibold text-verdict-allow transition-colors hover:bg-verdict-allow/25 disabled:opacity-50"
            >
              {reviewState === "approving" ? "Approving..." : "Approve"}
            </button>
            <button
              onClick={() => handleReview("deny")}
              disabled={isActioning}
              className="flex-1 rounded bg-verdict-block/15 px-3 py-2 text-xs font-semibold text-verdict-block transition-colors hover:bg-verdict-block/25 disabled:opacity-50"
            >
              {reviewState === "denying" ? "Denying..." : "Deny"}
            </button>
          </>
        )}
      </div>
    </div>
  );
}
